# Generated by Django 6.0.6 on 2026-06-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mylogo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mycontexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject_lesson', models.CharField(blank=True, choices=[('Ελληνικά', 'Ελληνικά'), ('Μαθηματικά', 'Μαθηματικά'), ('Ιστορία', 'Ιστορία'), ('Φυσική', 'Φυσική')], default='Ελληνικά', max_length=1000, null=True)),
                ('stage', models.CharField(blank=True, choices=[('Δημοτικού', 'Δημοτικού'), ('Γυμνασίου', 'Γυμνασίου'), ('Λυκείου', 'Λυκείου'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Δημοτικού', max_length=20, null=True)),
                ('class_is', models.CharField(blank=True, choices=[('Α΄ Τάξη', 'Α΄ Τάξη'), ('Β΄ Τάξη', 'Β΄ Τάξη'), ('Γ΄ Τάξη', 'Γ΄ Τάξη'), ('Δ΄ Τάξη', 'Δ΄ Τάξη'), ('Ε΄ Τάξη', 'Ε΄ Τάξη'), ('ΣΤ΄ Τάξη', 'ΣΤ΄ Τάξη'), ('Level A', 'Level A'), ('Level B', 'Level B'), ('Level C', 'Level C')], default='Α΄ Τάξη', max_length=1000, null=True)),
                ('edition', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('alt', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_chapter', models.IntegerField(blank=True, null=True)),
                ('price_all', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'My Contexts',
                'ordering': ['subject_lesson'],
                'constraints': [models.UniqueConstraint(fields=('title', 'subject_lesson', 'class_is', 'edition'), name='unique_context_per_class_level_edition')],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Τίτλος κεφαλαίου', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='homepage.mycontexts')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, help_text='π.χ. Σελίδα 25 - Δραστηριότητα 3 ή Θεωρία Κεφαλαίου', max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('part', models.CharField(blank=True, choices=[('', 'Ένα Video'), ('1', '1ο Μέρος'), ('2', '2ο Μέρος'), ('3', '3ο Μέρος'), ('4', '4ο Μέρος'), ('5', '5ο Μέρος'), ('6', '6ο Μέρος'), ('7', '7ο Μέρος'), ('8', '8ο Μέρος'), ('9', '9ο Μέρος')], default='', max_length=2)),
                ('video_url', models.URLField(blank=True)),
                ('sort', models.PositiveIntegerField(default=1)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='homepage.chapter')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['chapter__order', 'sort'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('context', 'title'), name='unique_chapter_per_context'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('context', 'order'), name='unique_chapter_order_per_context'),
        ),
        migrations.AddConstraint(
            model_name='videos',
            constraint=models.UniqueConstraint(fields=('chapter', 'page', 'part'), name='unique_video_location'),
        ),
    ]
