# Generated by Django 6.0.6 on 2026-06-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_chapter_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='title',
        ),
    ]
