# Generated by Django 6.0.6 on 2026-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_videos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontexts',
            name='includes',
            field=models.TextField(blank=True, help_text='Ένα στοιχείο ανά γραμμή.'),
        ),
    ]
