# Generated by Django 6.0.6 on 2026-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_mycontexts_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
