# Generated by Django 6.0.6 on 2026-06-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_videos_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontexts',
            name='stage',
            field=models.CharField(blank=True, choices=[('Δημοτικού', 'Δημοτικού'), ('Γυμνασίου', 'Γυμνασίου'), ('Λυκείου', 'Λυκείου')], default='Δημοτικού', max_length=20, null=True),
        ),
    ]
