# Generated by Django 6.0.6 on 2026-07-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_mycontexts_stage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.AlterField(
            model_name='mycontexts',
            name='class_is',
            field=models.CharField(blank=True, choices=[('Α΄ Τάξη', 'Α΄ Τάξη'), ('Β΄ Τάξη', 'Β΄ Τάξη'), ('Γ΄ Τάξη', 'Γ΄ Τάξη'), ('Δ΄ Τάξη', 'Δ΄ Τάξη'), ('Ε΄ Τάξη', 'Ε΄ Τάξη'), ('ΣΤ΄ Τάξη', 'ΣΤ΄ Τάξη')], default='Α΄ Τάξη', max_length=1000, null=True),
        ),
    ]
