# Generated by Django 6.0.6 on 2026-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_videos_video_alter_mycontexts_class_is'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Education', 'Education'), ('Languages', 'Languages'), ('Business', 'Business'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('alt', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('includes', models.TextField(blank=True, help_text='Ένα στοιχείο ανά γραμμή.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['title'],
            },
        ),
    ]
