# Generated by Django 6.0.6 on 2026-07-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Περιεχόμενο του training', max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_free', models.BooleanField(default=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_contents', to='homepage.training')),
            ],
            options={
                'verbose_name': 'Training Content',
                'verbose_name_plural': 'Training Contents',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('training', 'content'), name='unique_content_per_training'), models.UniqueConstraint(fields=('training', 'order'), name='unique_content_order_per_training')],
            },
        ),
    ]
