# Generated by Django 6.0.6 on 2026-07-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_trainingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image'), ('presentation', 'Presentation'), ('file', 'File'), ('link', 'External Link'), ('quiz', 'Quiz')], max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_free', models.BooleanField(default=False)),
                ('training_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='homepage.trainingcontent')),
            ],
        ),
    ]
