# Generated by Django 6.0.6 on 2026-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_trainingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcontent',
            name='description',
            field=models.TextField(blank=True, help_text='Περιγραφή του training'),
        ),
    ]
