# Generated by Django 6.0.6 on 2026-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_trainingcontent_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['chapter__order', 'page', 'part'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='sort',
        ),
        migrations.AddField(
            model_name='video',
            name='activity_title',
            field=models.CharField(blank=True, help_text="Περιγραφή της δραστηριότητας της σελίδας, π.χ. 'Εισαγωγή στο κεφάλαιο', 'Άσκηση 1', 'Άσκηση 2' κλπ.", max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='page',
            field=models.PositiveSmallIntegerField(default=1, help_text='Αριθμός σελίδας του βιβλίου'),
        ),
    ]
