# Generated by Django 6.0.6 on 2026-07-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_video_options_remove_video_sort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcontent',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='description',
        ),
    ]
