# Generated by Django 6.0.6 on 2026-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_remove_trainingcontent_is_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('terms_and_conditions', 'Όροι και Προϋποθέσεις'), ('privacy_policy', 'Πολιτική Απορρήτου'), ('announcements', 'Ανακοινώσεις'), ('faq', 'Συχνές Ερωτήσεις'), ('contact', 'Επικοινωνία')], max_length=50, unique=True, verbose_name='Σελίδα')),
                ('title', models.CharField(max_length=200)),
                ('path_image', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
