# Generated by Django 6.0.6 on 2026-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_informationpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpage',
            options={'ordering': ['order'], 'verbose_name': 'Σελίδα Πληροφόρησης', 'verbose_name_plural': 'Σελίδες Πληροφόρησης'},
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Σειρά εμφάνισης'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='path_image',
            field=models.URLField(max_length=500, verbose_name='Εικόνα'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Τίτλος'),
        ),
    ]
