# Generated by Django 6.0.6 on 2026-07-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_informationpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpage',
            name='app',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('accounts', 'Accounts')], default='homepage', max_length=20),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='page',
            field=models.CharField(choices=[('terms_and_conditions', 'Όροι και Προϋποθέσεις'), ('register', 'Εγγραφή'), ('privacy_policy', 'Πολιτική Απορρήτου'), ('announcements', 'Ανακοινώσεις'), ('faq', 'Συχνές Ερωτήσεις'), ('contact', 'Επικοινωνία')], max_length=50, unique=True, verbose_name='Σελίδα'),
        ),
    ]
