# Generated by Django 6.0.6 on 2026-07-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_informationpage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmaterial',
            name='url',
            field=models.TextField(help_text='Cloudinary video URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.TextField(help_text='Cloudinary video URL'),
        ),
    ]
