# Generated by Django 6.0.6 on 2026-07-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_trainingmaterial_url_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='url',
            field=models.TextField(blank=True, editable=False, help_text='Cloudinary video URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.TextField(blank=True, editable=False, help_text='Cloudinary video URL'),
        ),
    ]
