# Generated by Django 6.0.6 on 2026-07-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_trainingmaterial_video_file_video_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcontent',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='trainingcontent',
            constraint=models.UniqueConstraint(fields=('training', 'slug'), name='unique_slug_per_training'),
        ),
    ]
