# Generated by Django 6.0.6 on 2026-07-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_trainingcontent_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmaterial',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddConstraint(
            model_name='trainingmaterial',
            constraint=models.UniqueConstraint(fields=('training_content', 'order'), name='unique_material_order_per_content'),
        ),
    ]
