# Generated by Django 6.0.6 on 2026-07-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_alter_trainingmaterial_options_trainingmaterial_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingmaterial',
            name='unique_material_order_per_content',
        ),
    ]
