# Generated by Django 6.0.6 on 2026-07-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_remove_trainingmaterial_unique_material_order_per_content'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingmaterial',
            constraint=models.UniqueConstraint(fields=('training_content', 'slug'), name='unique_material_slug_per_content'),
        ),
        migrations.AddConstraint(
            model_name='trainingmaterial',
            constraint=models.UniqueConstraint(fields=('training_content', 'order'), name='unique_material_order_per_content'),
        ),
    ]
