# Generated by Django 6.0.6 on 2026-07-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_trainingmaterial_unique_material_slug_per_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('chapter__order', 'page', 'part'), 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='mycontexts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
