# Generated by Django 6.0.6 on 2026-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_video_options_chapter_slug_mycontexts_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontexts',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('context', 'slug'), name='unique_chapter_slug_per_context'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_video_slug_per_chapter'),
        ),
    ]
