# Generated by Django 6.0.6 on 2026-07-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_alter_mycontexts_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='page',
            field=models.CharField(choices=[('terms_and_conditions', 'Όροι και Προϋποθέσεις'), ('register', 'Register'), ('login', 'Sign In'), ('online_lessons', 'Online Μαθήματα'), ('announcements', 'Ανακοινώσεις'), ('faq', 'Συχνές Ερωτήσεις'), ('contact', 'Επικοινωνία'), ('about_us', 'Σχετικά με εμάς'), ('Refund Policy', 'Refund Policy'), ('Copyright Notice', 'Copyright Notice'), ('Privacy Policy', 'Privacy Policy')], max_length=50, unique=True, verbose_name='Σελίδα'),
        ),
    ]
