# Generated by Django 6.0.6 on 2026-07-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_alter_informationpage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='page',
            field=models.CharField(choices=[('terms_and_conditions', 'Όροι και Προϋποθέσεις'), ('register', 'Register'), ('login', 'Sign In'), ('online_lessons', 'Online Μαθήματα'), ('announcements', 'Ανακοινώσεις'), ('faq', 'Συχνές Ερωτήσεις'), ('contact', 'Επικοινωνία'), ('about_us', 'Σχετικά με εμάς'), ('refund_policy', 'Refund Policy'), ('copyright_notice', 'Copyright Notice'), ('privacy_policy', 'Privacy Policy')], max_length=50, unique=True, verbose_name='Σελίδα'),
        ),
    ]
