# Generated by Django 6.0.6 on 2026-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_alter_informationpage_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='material_public_id',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='video_public_id',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
