# Generated by Django 6.0.6 on 2026-07-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_remove_trainingmaterial_url_remove_video_video_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingmaterial',
            old_name='material_public_id',
            new_name='stream_uid',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_public_id',
            new_name='stream_uid',
        ),
    ]
