# Generated by Django 6.0.6 on 2026-07-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_rename_material_public_id_trainingmaterial_stream_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='cloudflare_status',
            field=models.CharField(default='pending', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='cloudflare_uid',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='cloudflare_status',
            field=models.CharField(default='pending', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='cloudflare_uid',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
