# Generated by Django 6.0.6 on 2026-07-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_trainingmaterial_cloudflare_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='stream_uid',
        ),
        migrations.RemoveField(
            model_name='video',
            name='stream_uid',
        ),
    ]
