# Generated by Django 6.0.6 on 2026-07-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_remove_trainingmaterial_stream_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cloudflare_ready',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='cloudflare_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='cloudflare_uid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
    ]
