# Generated by Django 6.0.6 on 2026-08-06 09:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_video_cloudflare_ready_alter_video_cloudflare_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, help_text='Βάλε URL της εικόνας', max_length=1000, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company Informations',
                'ordering': ['id'],
            },
        ),
    ]
