# Generated by Django 6.0.6 on 2026-08-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpage',
            name='app',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='page',
        ),
    ]
