# Generated by Django 6.0.6 on 2026-08-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_remove_informationpage_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modal_info', to='homepage.informationpage'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
