# Generated by Django 6.0.6 on 2026-08-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_informations_page_alter_informations_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mycontexts',
            new_name='Schoolcontexts',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='SchoolVideo',
        ),
        migrations.RenameModel(
            old_name='TrainingMaterial',
            new_name='TrainingVideo',
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'School Chapter', 'verbose_name_plural': 'School Chapters'},
        ),
        migrations.AlterModelOptions(
            name='schoolcontexts',
            options={'ordering': ['subject_lesson'], 'verbose_name_plural': 'School Contexts'},
        ),
        migrations.AlterModelOptions(
            name='schoolvideo',
            options={'ordering': ('chapter__order', 'page', 'part'), 'verbose_name': 'School Video', 'verbose_name_plural': 'School Videos'},
        ),
        migrations.AlterModelOptions(
            name='trainingcontent',
            options={'ordering': ['order'], 'verbose_name': 'Training Chapter', 'verbose_name_plural': 'Training Chapters'},
        ),
        migrations.AlterModelOptions(
            name='trainingvideo',
            options={'ordering': ['order'], 'verbose_name': 'Training Video', 'verbose_name_plural': 'Training Videos'},
        ),
    ]
