# Generated by Django 6.0.6 on 2026-08-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_rename_mycontexts_schoolcontexts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolcontexts',
            options={'ordering': ['subject_lesson'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
    ]
