# Generated by Django 6.0.6 on 2026-08-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_alter_schoolcontexts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'ordering': ['id'], 'verbose_name': 'Legal Information', 'verbose_name_plural': 'Legal Information'},
        ),
    ]
