# Generated by Django 6.0.6 on 2026-08-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0038_alter_informations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpage',
            options={'ordering': ['order'], 'verbose_name': 'Card for Legal Information', 'verbose_name_plural': 'Cards for Legal Information'},
        ),
    ]
