# Generated by Django 6.0.6 on 2026-08-08 19:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_alter_informationpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontexts',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
