# Generated by Django 6.0.6 on 2026-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_alter_informationpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontexts',
            name='image',
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='image',
            ),
        ),
    ]