# Generated by Django 6.0.6 on 2026-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_alter_schoolcontexts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontexts',
            name='class_is',
            field=models.CharField(blank=True, choices=[('Α΄ Τάξη', 'Α΄ Τάξη'), ('Β΄ Τάξη', 'Β΄ Τάξη'), ('Γ΄ Τάξη', 'Γ΄ Τάξη'), ('Δ΄ Τάξη', 'Δ΄ Τάξη'), ('Ε΄ Τάξη', 'Ε΄ Τάξη'), ('ΣΤ΄ Τάξη', 'ΣΤ΄ Τάξη'), ('Α΄- ΣΤ΄ Τάξη', 'Α΄- ΣΤ΄ Τάξη')], default='Α΄ Τάξη', max_length=1000, null=True),
        ),
    ]
