# Generated by Django 6.0.6 on 2026-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_alter_schoolcontexts_class_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Mathematics', 'Μαθηματικά'), ('Education', 'Education'), ('Languages', 'Languages'), ('Business', 'Business'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
