# Generated by Django 6.0.6 on 2026-08-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_rename_trainingcontent_to_topicscontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['title'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='topicscontent',
            options={'ordering': ['order'], 'verbose_name': 'Topic Chapter', 'verbose_name_plural': 'Topic Chapters'},
        ),
        migrations.AlterModelOptions(
            name='topicsvideo',
            options={'ordering': ['order'], 'verbose_name': 'Topic Video', 'verbose_name_plural': 'Topic Videos'},
        ),
        migrations.RemoveConstraint(
            model_name='topicscontent',
            name='unique_content_per_training',
        ),
        migrations.RemoveConstraint(
            model_name='topicscontent',
            name='unique_content_order_per_training',
        ),
        migrations.RemoveConstraint(
            model_name='topicscontent',
            name='unique_slug_per_training',
        ),
        migrations.RemoveConstraint(
            model_name='topicsvideo',
            name='unique_material_slug_per_content',
        ),
        migrations.RemoveConstraint(
            model_name='topicsvideo',
            name='unique_material_order_per_content',
        ),
        migrations.AlterField(
            model_name='topicscontent',
            name='content',
            field=models.CharField(help_text='Περιεχόμενο του topics', max_length=200),
        ),
        migrations.AlterField(
            model_name='topicscontent',
            name='description',
            field=models.TextField(blank=True, help_text='Περιγραφή του topics'),
        ),
        migrations.AlterField(
            model_name='topicscontent',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_contents', to='homepage.topics'),
        ),
        migrations.AddConstraint(
            model_name='topicscontent',
            constraint=models.UniqueConstraint(fields=('topics', 'content'), name='unique_content_per_topics'),
        ),
        migrations.AddConstraint(
            model_name='topicscontent',
            constraint=models.UniqueConstraint(fields=('topics', 'slug'), name='unique_slug_per_topics'),
        ),
        migrations.AddConstraint(
            model_name='topicscontent',
            constraint=models.UniqueConstraint(fields=('topics', 'order'), name='unique_content_order_per_topics'),
        ),
        migrations.AddConstraint(
            model_name='topicsvideo',
            constraint=models.UniqueConstraint(fields=('topics_content', 'slug'), name='unique_material_slug_per_content'),
        ),
        migrations.AddConstraint(
            model_name='topicsvideo',
            constraint=models.UniqueConstraint(fields=('topics_content', 'order'), name='unique_material_order_per_content'),
        ),
    ]
