# Generated by Django 6.0.6 on 2026-08-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_alter_topics_options_alter_topicscontent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='is_published',
        ),
    ]
