# Generated by Django 6.0.6 on 2026-08-16 07:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0046_remove_topics_is_free_remove_topics_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='created',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='updated',
        ),
        migrations.AlterField(
            model_name='topics',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='includes',
            field=models.TextField(blank=True, help_text='Τι περιλαμβάνει. Ένα στοιχείο ανά γραμμή.'),
        ),
    ]
