# Generated by Django 6.0.6 on 2026-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0047_remove_topics_created_remove_topics_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Βασικό'), ('Intermediate', 'Ενδιάμεσο'), ('Advanced', 'Προχωρημένο')], default='Beginner', max_length=30),
        ),
    ]
