# Generated by Django 6.0.6 on 2026-08-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0048_alter_topics_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolvideo',
            name='topics_contents',
            field=models.ManyToManyField(blank=True, related_name='school_videos', to='homepage.topicscontent'),
        ),
    ]
