# Generated by Django 6.0.6 on 2026-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0049_schoolvideo_topics_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicscontent',
            name='content',
            field=models.CharField(help_text='Περιγραφή του topics. Γραψε μια συντομη περιγραφή 4-5 γραμμων.', max_length=200),
        ),
        migrations.AlterField(
            model_name='topicscontent',
            name='description',
            field=models.TextField(blank=True, help_text="Περιγραφή του video. Γραψε μια συντομη περιγραφή π.χ 'Γεωμετρια - Θεωρια'."),
        ),
    ]
