# Generated by Django 6.0.6 on 2026-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0050_alter_topicscontent_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicscontent',
            name='content',
            field=models.CharField(help_text="Τίτλος Περιεχομένου π.χ 'Εισαγωγή στη Γεωμετρία' ", max_length=1000),
        ),
        migrations.AlterField(
            model_name='topicscontent',
            name='description',
            field=models.CharField(blank=True, help_text="Περιγραφή του video. Γραψε μια συντομη περιγραφή π.χ 'Γεωμετρια - Θεωρια'.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='topicscontent',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000),
        ),
    ]
