# Generated by Django 6.0.6 on 2026-10-01 13:48

import homepage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0052_userpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontexts',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='schools/'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='topics/'),
        ),
    ]
