# Generated by Django 6.0.6 on 2026-10-01 20:26

import homepage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0053_alter_schoolcontexts_image_alter_topics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='mylogo',
            field=models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='logos/'),
        ),
    ]
