# Generated by Django 6.0.6 on 2026-10-01 20:31

import homepage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0054_alter_logo_mylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='path_image',
            field=models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='information-pages/', verbose_name='Εικόνα'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='informations/'),
        ),
    ]
