# Generated by Django 6.0.6 on 2026-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0055_alter_informationpage_path_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsvideo',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
