# Generated by Django 6.0.6 on 2026-10-02 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0056_topicsvideo_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='homepage.topics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Purchase',
                'verbose_name_plural': 'Topic Purchases',
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_topic_purchase_per_user')],
            },
        ),
    ]
