# Generated by Django 6.0.6 on 2026-10-06 08:55

import homepage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0057_topicpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mylogo', models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='logos/')),
            ],
        ),
    ]
