# Generated by Django 6.0.6 on 2026-10-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0058_successlogo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccessLogo',
            new_name='FooterLogo',
        ),
    ]
