# Generated by Django 6.0.6 on 2026-10-06 10:12

import homepage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0059_rename_successlogo_footerlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=homepage.storage.get_r2_storage, upload_to='backgrounds/')),
            ],
        ),
    ]
